const actionTypes:AppNS.IActionTypes = {
    'APP_SET_INITIAL_GAME_GRID': 'APP_SET_INITIAL_GAME_GRID',
    'APP_SET_SELECTED_DIFFICULTY_LEVEL':'APP_SET_SELECTED_DIFFICULTY_LEVEL',
    'APP_CLEAR_STATE':'APP_CLEAR_STATE', 
    'APP_SET_CLICKED_CELL': 'APP_SET_CLICKED_CELL',
};

export default actionTypes;